### PR TITLE
Docker config

### PR DESCRIPTION
**Pull request by kurtisnelson**
Like #6 but shorter.

### CODE REVIEW

**Comment by jah2488** [comment]
I'm guessing This(#9) is supposed to replace #6 then?

**Comment by kurtisnelson** [comment]
Yeah, someone else should test it with `docker-compose up`

**Comment by jah2488** [comment]
```
web_1 | ! Unable to load application: ExecJS::RuntimeUnavailable: Could not find a JavaScript runtime. See https://github.com/sstephenson/execjs for a list of available runtimes.
```

**Comment by jah2488** [comment]
I guess I should just merge this is in and we can deal with the issues with it later as they come up.

**Pull request merged**
