### PR TITLE
Instructor can enroll user

### PR DESCRIPTION
**Pull request by kurtisnelson**
Removes the materialize sheet because it was not playing well with normal bootstrap overrides.
I went through the whole app and cleaned up anything that was awkward, we can get the materialness back just by overriding .btn ourselves I think.

### CODE REVIEW

**Comment by kurtisnelson** [comment]
I apologize for the general terribleness that is this PR.

**Comment by kurtisnelson** [comment]
Absolutely ugly, but if an instructor goes to /students/new they can enlist a User in their Cohort.

**Comment by kurtisnelson** [comment]
Closes #103

**Comment by kurtisnelson** [comment]
Successfully scoped back down to just the enroll widget. Can someone try it out?

**Comment by jah2488** [comment]
Oh dammit, forgot about this PR when merging in the materialize one. Hopefully that didn't break this too much.

**Pull request merged**
