### PR TITLE
Google OAuth login

### PR DESCRIPTION
**Pull request by kurtisnelson**
Working oauth login + automatic instructor grant to TIY emails.

### CODE REVIEW

**Comment by jah2488** [comment]
That was fast.

**Comment by kurtisnelson** [comment]
(insert something about me combining the devise models earlier here) :trollface:

**Comment by jah2488** [comment]
:+1: 

Something conflicted with the other PRs, as soon as we get that fixed I'll merge this in.

**Comment by kurtisnelson** [comment]
Fixed.

**Pull request merged**
