### PR TITLE
[Proposal] - Setup Vagrantfile For VM Use

### PR DESCRIPTION
**Pull request by rtablada**
I'm not sure if I'm just doing it completely wrong, but I seem to have issues with my different ruby gems even with RVM and Bundler.

At my past company, we used Vagrant to manage VMs so that global gems couldn't conflict.

I'm not a big rails guy and I've tried my best to get this to work, but there's still probably some stuff to go.

So far I have:

* Installed RVM & Ruby 2.2.2 (configurable in the vagrantfile)
* Installed Postgres
* Installed `bundler`
* Installed Nginx and config based on the Digital Ocean article on Puma + Ngnix

I'm getting an error when I try `script/setup`

```
An error occurred while installing pg (0.18.1), and Bundler cannot continue.
Make sure that `gem install pg -v '0.18.1'` succeeds before bundling.
```

This PR isn't ready to go until some stuff is figured out. But I want to get things started.

Also, idk if Docker is a bit of a better choice? I'm just going with what I knew and was able to toss together. I've seen other projects on Docker.

### CODE REVIEW

**Comment by jah2488** [comment]
Honestly, I've never used docker outside of demoing it here and there. So I don't think I'm real qualified to vet if this is working or not. However, if a lot of other people are planning on working on the app then it is probably worth getting this up and running. I'll look this over more tomorrow when I can.

The pg might be because you have some other de dependencies that aren't met. Have you installed postgres through homebrew?

**Comment by jah2488** [comment]
%s/docker/vagrant/

**Comment by rtablada** [comment]
So with Vagrant, everything would be running on an Ubuntu VM. The vagrant config file installs rvm and pg on the virtual machine.

At the end of things you would run vagrant ssh and the /vagrant/script/server and the app would be up and running on 192.168.22.10:3000 (or whatever port you have rails set up to be on).

**Comment by rtablada** [comment]
We could also port forward so that localhost:3001 or something forwards to the right port on the VM. This can also be used to test the mix of nginx + puma

**Comment by jah2488** [comment]
Very cool. I'll check this out today and get it merged in.

**Comment by kurtisnelson** [comment]
I'll also check. I agree docker is nice for non-rails people to work with the app, but any rails dev is going to hate not having hot reload.

**Comment by rtablada** [comment]
@kurtisnelson you can set up vagrant or docker to hot reload (using `rake serve` or whatever's cool these days)

**Comment by jah2488** [comment]
Closing in favor of #9

**Pull request closed without merging**
