### PR TITLE
Ability to update a report as staff, with existing edit button

### PR DESCRIPTION
**Pull request by jwo**
Here's that button
classroom_and_jwos-macbook-air_ _-zsh_ _129x35

### CODE REVIEW

**Comment by kurtisnelson** [comment]
Travis is very very unhappy.

**Comment by jwo** [comment]
So in @kurtisnelson latest build that worked, travis logs this:

```
Setting environment variables from repository settings

$ export ASSET_HOST=example.com

$ export GOOGLE_CLIENT_ID=[secure]

$ export GOOGLE_CLIENT_SECRET=[secure]

$ export mandrill_api_key=[secure]

$ export CODECLIMATE_REPO_TOKEN=[secure]

$ export AWS_ID=

$ export AWS_SECRET=

$ export S3_BUCKET=
```

But in mine, it totally doesn't use the env variables:

```
Setting environment variables from repository settings

$ export ASSET_HOST=example.com

$ export AWS_ID=

$ export AWS_SECRET=

$ export S3_BUCKET=
```

I'm going to have it refresh and watch it fail again, just to see

**Comment by jwo** [comment]
Wait I can't do that.

**Comment by kurtisnelson** [comment]
Pulled the branch locally, had much success. Travis is not loading in the ENV on your fork and failing.

**Pull request merged**
